services:
  php:
    volumes:
      - ./app:/var/www/html:delegated
    environment:
      APP_ENV: dev
      APP_DEBUG: 1

  nginx:
    volumes:
      - ./app:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  composer:
    build:
      context: .
      dockerfile: docker/composer/Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
      - ${HOME}/.cache/composer:/tmp/composer/cache
    environment:
      COMPOSER_HOME: /tmp/composer
    entrypoint: ["composer"]

  node:
    image: node:20-alpine
    working_dir: /app
    command: sh -lc "npm install && npm run dev -- --watch"
    volumes:
      - ./app:/app

  db:
    ports:
      - "55432:5432"
