services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: app
    image: my-symfony-app:prod
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        RUNTIME_IMAGE: my-symfony-app:prod
    ports:
      - "8080:80"
    depends_on:
      - php

  db:
    image: mariadb:10.6.21
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:

