apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-app
  namespace: symfony
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfony-app
  template:
    metadata:
      labels:
        app: symfony-app
    spec:
      containers:
        - name: app
          image: my-symfony-app:prod
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-config
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          # Optional: PHP-FPM Socket/Port check via exec, when it makes sense in the image
          # lifecycle:
          #   postStart:
          #     exec: { command: ["bash","-lc","php bin/console cache:clear --env=prod || true"] }
