apiVersion: v1
kind: Service
metadata:
  name: symfony-app
  namespace: symfony
spec:
  type: NodePort
  selector:
    app: symfony-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080  # choose from allowed range (30000-32767)
