apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: symfony
type: Opaque
stringData:
  MARIADB_DATABASE: app
  MARIADB_USER: app
  MARIADB_PASSWORD: app
  MARIADB_ROOT_PASSWORD: root
