apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 80
      # Kubernetes chooses the NodePort; when you want a fix port, add nodePort: 31080 (30000–32767) - for instance
