name: Code Quality

on:
  push:
    branches:
      - main # Trigger for main branch
defaults:
  run:
    working-directory: app

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, dom, xml, xmlwriter, pdo_pgsql
          coverage: none
          ini-values: memory_limit=-1

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: composer-${{ hashFiles('app/composer.lock') }}
          restore-keys: composer-

      - name: Assert composer.json exist
        run: test -f composer.json || { echo "::error ::app/composer.json is missing"; exit 1; }

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPStan
        run: |
          if [ -x "vendor/bin/phpstan" ]; then
            vendor/bin/phpstan analyse --no-progress
          else
            echo "::warning ::phpstan is missing (require-dev) – step skipped"
          fi

      - name: Run PHPCS
        run: |
          if [ -x "vendor/bin/phpcs" ]; then
            vendor/bin/phpcs
          else
            echo "::warning ::phpcs is missing (require-dev) – step skipped"
          fi
