name: K8s Build (no deploy on local)

on:
  push:
    branches: [ feature/k8s-symfony ]
    paths:
      - "app/**"
      - "docker/**"
      - "k8s/**"
      - ".github/workflows/k8s-deploy.yml"

permissions:
  contents: read
  packages: write  # only necessary, when you will push in GHCR

env:
  IMAGE: ghcr.io/${{ github.repository }}/symfony-app

jobs:
  build_image:
    name: "Build image (no push)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional: only for validate, without push
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ env.IMAGE }}:ci-test

  # Optional: when you will push in GHCR (for later 'minikube image load' from your own computer)
  push_image:
    name: "Push image to GHCR (optional)"
    runs-on: ubuntu-latest
    needs: [build_image]
    if: ${{ false }} # set true, when you really want to push
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
